"""empty message

Revision ID: 71897cc2bfb7
Revises: b3bb62fc0e20
Create Date: 2018-10-05 23:55:01.195709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71897cc2bfb7'
down_revision = 'b3bb62fc0e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classified_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classified_ad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ads_tags_rel',
    sa.Column('ad_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['classified_ad.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['classified_tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ads_tags_rel')
    op.drop_table('classified_ad')
    op.drop_table('classified_tags')
    # ### end Alembic commands ###
